# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff3d335a4ef53a5af21842ee77394b925bd4c1c2a0917e85823ea016804345e4d17a84c4e2a1a2b40c0d7caab70e20a4a3c71a1b555c99d16cf3ac3979b9479

test:
  secret_key_base: 06cf1d7260343335731c2c26ee935636d8de5966f77ed1463c0acf1679038b64099679a39f12d61365d3cf9f4fa0261bf452eb6f5d47fbee53f13b6ed8f4605c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
